### ISSUE TITLE
[Bug] 添加插件配置后，面板没有更新数据，聊天也没有触发插件效果

### ISSUE THREAD

**Issue by Moonlit7** [lobehub/chat-plugin-sdk#24]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

根据文档说明，添加manifest配置后，面板数据没有更新
<img width="1094" alt="image" src="https://github.com/lobehub/chat-plugin-sdk/assets/2390305/dfc67095-1ba9-4155-9301-1f753e99f996">
回到聊天窗口，发送指令没有调用插件
<img width="826" alt="image" src="https://github.com/lobehub/chat-plugin-sdk/assets/2390305/f60cb0d6-1451-440d-9005-478bd2189c8a">

### 🚦 期望结果 | Expected Behavior

正确调用插件

### 📝 补充信息 | Additional Information

lobe-chat版本：0.89.6
插件模版版本：1.1.0

**Comment by arvinxx** [comment]
> https://chat-plugin-sdk.lobehub.com/guides/get-start
> 这边漏掉了一步，manifest-dev.json要先修改identifier

理论上不修改 identifier 应该也能跑的
