### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by ifsheldon** [lobehub/chat-plugin-sdk#37]
https://chat-plugin-sdk.lobehub.com/guides/plugin-server#support-for-openapi-manifest here says support for OpenAPI manifest is tracked at https://github.com/lobehub/lobe-chat/issues/550 . The tracking issue has been closed, suggesting that the feature is ready, but I don't see any new instructions in the documentation to guide how to do this. Please consider update the documentation.

**Comment by arvinxx** [comment]
We are working on this. Please stay tuning. Refs: https://github.com/lobehub/lobe-chat/discussions/411
